//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rule.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_users
    {
        public int id { get; set; }
        public string role { get; set; }
    
        public virtual users users { get; set; }
    }
}
